### ISSUE TITLE
带佬，那个菜鸟裹裹

### ISSUE THREAD

**Issue by 1162363196** [syhien/XiQi-Auto.js#1]
菜鸟裹裹为什么点开不能做任务呢，能跳转就是没有做任务，好可惜😳😳

**Comment by syhien** [comment]
我很久没管梦工厂了，不做任务应该是脚本无法适配目前的活动了
这个活动时不时变一下界面、变一下视图，每次都要改代码，碰巧当时出了更好的活动喜气红包，我就渐渐弃养这个脚本了（
auto.js很好入门，你有兴趣的话可以试试在我的基础上修改（甚至写属于自己的脚本）

**Comment by 1162363196** [comment]
嗯嗯，好的，我也打算研究怎么做这个脚本，感觉这个合成金宝裹挺方便的，就是不知道怎么入门呢，需要掌握什么语言呢Java 和c语言吗？有没有入门的指南车
(   ˊ ᵕ ˋ 💦)看哪里的视频然后开始尝试呢？😳

**Comment by syhien** [comment]
嗯 auto.js用的语言是javascript，js和蛮多语言都蛮像的，也很好上手，照着写几次就会了
我当时主要看的教程一个是 [一篇知乎](https://zhuanlan.zhihu.com/p/90065914) 另一个就是需要的时候翻找的 [官方文档](https://hyb1996.github.io/AutoJs-Docs/#/)
auto.js免费版已经不维护了，可以去自行编译（我自己编了一份，勉强能用）；auto.js pro是一次性付费，体验不错子。

**Comment by syhien** [comment]
[编译的apk](https://github.com/syhien/Auto.js/releases)

**Comment by 1162363196** [comment]
嗯嗯，现在假期在开始跟着哔哩哔哩黑马学习Java，争取能学以致用，谢谢老哥的分享
